# Generated by Django 3.2.8 on 2022-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='created_on',
        ),
        migrations.AddField(
            model_name='courses',
            name='requirements',
            field=models.CharField(default='N/a', max_length=2550),
        ),
    ]
